name: reviewdog
on: workflow_call

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1

# For AsciiDoc users:
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

# For reStructuredText users:
      - name: Install docutils
        run: sudo apt-get install -y docutils